spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    #url: jdbc:mysql://127.0.0.1:3306/keyuanshucheng
    username: root
    password:


server:
  port: 8080
  servlet.context-path: /   #项目名前缀

mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

logging:
  level:
    com.yc.kysc.dao: debug


